#BERTopic on UNTM Sample Dataset
In this notebook I have implemented Topic Modeling on Urdu News Data transformer based topic modelling technique BERTopic.

## Mounting Google Drive
If the dataset is on Google Drive then you have to mount over google drive with collaboratory.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



#Installing required dependencies
**One thing to remember is that after installing libraries you have to restart the run time again so that other dependencies are not affected by it.**

In [ ]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.16.0-py2.py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.1/154.1 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.23.5)
Collecting hdbscan>=0.8.29 (from bertopic)
  Downloading hdbscan-0.8.33.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 11.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting umap-learn>=0.5.0 (from bertopic)
  Downloading umap-learn-0.5.5.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.9/90.9 kB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.5.3)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.2.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (4.66.1)
Collecting sentence-transformers>=0.4.1 (from bertopic)
  Downloading sentence_transformers-2.3.1-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 13.6 MB/s eta 0:00:00
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (5.15.0)
Collecting cython<3,>=0.27 (from hdbscan>=0.8.29->bertopic)
  Using cached Cython-0.29.37-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.11.4)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2023.4)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (23.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.2.0)
Requirement already satisfied: transformers<5.0.0,>=4.32.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.35.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.1.0+cu121)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (9.4.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->bertopic) (0.58.1)
Collecting pynndescent>=0.5 (from umap-learn>=0.5.0->bertopic)
  Downloading pynndescent-0.5.11-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 6.5 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (4.5.0)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.41.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.3)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (2023.12.25)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (0.4.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers>=0.4.1->bertopic) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Building wheels for collected packages: hdbscan, umap-learn
  Building wheel for hdbscan (pyproject.toml) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.33-cp310-cp310-linux_x86_64.whl size=3039290 sha256=220acaad32e2b77fab4733bd6a04a153821367e51899f6bc8196397eccf343ca
  Stored in directory: /root/.cache/pip/wheels/75/0b/3b/dc4f60b7cc455efaefb62883a7483e76f09d06ca81cf87d610
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.5-py3-none-any.whl size=86832 sha256=00da79317140e38a6cccfd3bee0c0d153e14be3e1878e4a7c3fd855c426a8e54
  Stored in directory: /root/.cache/pip/wheels/3a/70/07/428d2b58660a1a3b431db59b806a10da736612ebbc66c1bcc5
Successfully built hdbscan umap-learn
Installing collected packages: cython, pynndescent, hdbscan, umap-learn, sentence-transformers, bertopic
  Attempting uninstall: cython
    Found existing installation: Cython 3.0.8
    Uninstalling Cython-3.0.8:
      Successfully uninstalled Cython-3.0.8
Successfully installed bertopic-0.16.0 cython-0.29.37 hdbscan-0.8.33 pynndescent-0.5.11 sentence-transformers-2.3.1 umap-learn-0.5.5

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: transformers<5.0.0,>=4.32.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.1.0+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.3)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (2023.12.25)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (0.4.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)

In [ ]:
!pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.12.0)
Collecting tensorflow
  Downloading tensorflow-2.15.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 1.0 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.35.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.60.0)
Collecting tensorboard<2.16,>=2.15 (from tensorflow)
  Downloading tensorboard-2.15.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 21.4 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 30.3 MB/s eta 0:00:00
Collecting keras<2.16,>=2.15.0 (from tensorflow)
  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 41.5 MB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.42.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.17.3)
Collecting google-auth-oauthlib<2,>=0.5 (from tensorboard<2.16,>=2.15->tensorflow)
  Downloading google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.4)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)
Installing collected packages: tensorflow-estimator, keras, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.12.0
    Uninstalling tensorflow-estimator-2.12.0:
      Successfully uninstalled tensorflow-estimator-2.12.0
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.12.0
    Uninstalling tensorboard-2.12.0:
      Successfully uninstalled tensorboard-2.12.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.12.0
    Uninstalling tensorflow-2.12.0:
      Successfully uninstalled tensorflow-2.12.0
Successfully installed google-auth-oauthlib-1.2.0 keras-2.15.0 tensorboard-2.15.1 tensorflow-2.15.0.post1 tensorflow-estimator-2.15.0


# Importing required dependencies
We will import numpy, pandas and re, bertopic, gensim library for now. other libraries will be imported in the notebook later.

Pandas will be used to create a Dataframe and handle the csv file. Numpy will be used for the faster computation of arrays to save time. re library will be used for the cleaning of data. gensim library is used to get coherence score. bertopic is used to train bertopic on our UNTM dataset with using pretrained language models

In [ ]:
import pandas as pd
import numpy as np
import re
from bertopic import BERTopic
from gensim.models.coherencemodel import CoherenceModel
import gensim.corpora as corpora
#optional
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.ERROR)

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

##DataFrame

In [ ]:
#load UNTM Dataset
df = pd.read_csv('/content/drive/MyDrive/sampled_UNTM.csv', encoding='utf-8')

In [ ]:
print(len(df))
df.head()

399

,Date,Title,News,Category,Link,Clean_Data
0,2023-03-02,چیئرمین آئی پی او کا کاپی رائٹس سٹیک ہولڈرز کے...,لاہور (اُردو پوائنٹ اخبارتازہ ترین - اے پی پی۔...,Business,https://www.urdupoint.com/business/news-detail...,انٹلیکچوئل پراپرٹی رائٹس آرگنائزیشن کے چیئرم...
1,2023-03-17,سٹیٹ بینک پارلیمنٹ کے ایوان بالا کی گولڈن جوبل...,اسلام آباد (اُردو پوائنٹ اخبارتازہ ترین - اے پ...,Business,https://www.urdupoint.com/business/news-detail...,سٹیٹ بینک پارلیمنٹ کے ایوان بالا سینیٹ کی گول...
2,2023-04-19,دیر چیمبر آف کامرس اینڈ انڈسٹری کی تعاون سے دی...,دیر لو ئر، 19 اپریل (اُردو پوائنٹ اخبارتازہ تر...,Business,https://www.urdupoint.com/business/news-detail...,ڈپٹی کمشنر کمانڈنٹ دیر لیویز افتخار احمد اور ...
3,2023-04-05,سیالکوٹ چیمبر آف کامرس کا شیخ ریاض الدین اور خ...,سیالکوٹ (اُردو پوائنٹ اخبارتازہ ترین - اے پی پ...,Business,https://www.urdupoint.com/business/news-detail...,سیالکوٹ چیمبر آف کامرس کے سینئر نائب صدر وہب ...
4,2023-04-21,برازیل میں ہائبرڈ گاڑیوں کی تیاری کے لیے 34 کر...,ٹوکیو (اُردو پوائنٹ اخبارتازہ ترین - اے پی پی۔...,Business,https://www.urdupoint.com/business/news-detail...,جاپان کی کار ساز کمپنی ٹویوٹا نے کہا ہے کہ وہ...

## Preprocessing of Data
Data was cleaned that saved into column "Clean_Data" we  removed some extra coloumns first like date,Title,Link and some other columns too. Because we do experiment only news  and all other things are extra for us.

Stopwords are common words that are often filtered out during text processing in natural language processing (NLP) tasks. These words are considered to have little or no value in conveying the actual meaning of the text. We take list of 401 stopwords for topic modelling.

In [ ]:
df=df.drop(columns=['Date','Title', 'Link'])

In [ ]:
def remove_nonbreaking_space(text):
    return re.sub(r'\xa0', ' ', text)

df['Clean_Data'] = df['Clean_Data'].apply(remove_nonbreaking_space)

In [ ]:
documents = df['Clean_Data'].values.tolist()
print((documents[1]))

 سٹیٹ بینک پارلیمنٹ کے ایوان بالا سینیٹ کی گولڈن جوبلی کے موقع پر  روپے کا یادگاری سکہ جاری کرے گا۔سٹیٹ بینک کی جانب سے جاری اعلامیہ کے مطابق سینیٹ آف پاکستان جو کہ آئینی طور پر ہاؤس آف فیڈریشن ہے پاکستان کی دو ایوانوں پر مشتمل پارلیمنٹ کی قانون سازی کا بالائی چیمبر ہے کی تشکیل کی  سال مکمل ہونے پر  روپے کا یادگاری سکہ جاری کیا جائے گا ۔ اعلامیہ میں کہا گیا ہے کہ سینٹ آف پاکستان میں پاکستان کے تمام صوبوں کو مساویانہ نمائندگی دی گئی ہے یہ ایک مستقل ایوان ہے جو قومی امور کے پروسیس میں تسلسل کی علامت ہے۔ سال ء پاکستان کے سینٹ کی گولڈن جوبلی کا سال ہے۔ اس خصوصی موقع کی مناسبت سے وفاقی حکومت نے سٹیٹ بینک کو  روپے کا یادگاری سکہ جاری کرنے کی اجازت دی ہے۔     یہ یادگاری سکہ  مارچ ء سے ایس بی پی بینکنگ سروسز کارپوریشن کے فیلڈ دفاتر کے تمام تبادلہ کاؤنٹرز سے جاری کیا جائے گا۔ روپے کے یادگاری سکے کی شکل گول ہے جسے  ملی میٹر سمت کے ساتھ نقش کیا گیا ہے اس کا وزن  گرام اور یہ تانبے اور نکل کے دھاتی اجزا  پرمشتمل ہے۔ سکے کے سامنے کے رخ کے درمیان میں بڑھتا ہوا ہلالی چاند اور پانچ نوکوں پر مشتمل ستارہ دیا گیا ہے جس کا رخ شمال مغرب کی طرف ہے۔ سکے کے دائرے کے ساتھ چاند ستارے کے اوپر  اسلامی جمہوریہ پاکستان  کے الفاظ اردو سکرپٹ میں کندہ کیے گئے ہیں۔ چاند کے نیچے اور گندم کی اوپر کو اٹھتی ہوئی دو شاخوں کے اوپر سکے کے اجرا کا سال  تحریر ہے۔ سکے کی ظاہری مالیت ابھرے ہوئے اعداد میں اور روپیہ  اردو سکرپٹ میں بالترتیب چاند ستارے کے دائیں اور بائیں جانب تحریر کیے گئے ہیں۔ سکے کی پچھلی طرف اور سکے کے مرکز میں سینیٹ آف پاکستان کے امتیازی نشان کو  کے فنکارانہ عددی الفاظ کے ساتھ دیا گیا ہے جو اس کے دائیں جانب ہے۔ اس امتیازی نشان کے اوپر دائرے کے ساتھ اردو اسکرپٹ میں  پاکستان سینٹ گولڈن جوبلی کے الفاظ کندہ ہیں۔ سینٹ کے امتیازی نشان کے نیچے گولڈن جوبلی کی مدت  درج ہے۔

In [ ]:
import nltk
stopwords=pd.read_csv('/content/drive/MyDrive/stopwords.txt',names=['List'])
# stopwords['List']

stopwords_ur=[]
for li in stopwords['List']:
  stopwords_ur.append(li)
print(len(stopwords_ur))
print(stopwords_ur)

401
['کی', 'ہیں', 'ہے', 'رہا', 'رہی', 'رہے', 'تھا', 'تھے', 'تھی', 'تھى', 'میں', 'کہ', 'کے', 'ہوتے', 'کہہ', 'بنانا', 'پھر', 'لکین', 'ہوتی', 'لیتی', 'ایسی', 'ائے', 'ہوئے', 'ہوۓ ', 'مگر', 'چاہے', 'کیے', 'تاکہ', 'تم', 'آکر', 'لگا', 'ہوگیئں', 'ليے', 'رہتی', 'ہوگئی', 'انھوں', 'چاہتے', 'پاگیئں', 'آنا', 'کروا', 'رکھ', 'آتی', 'یہاں', 'جیسا', 'چکے', 'کرئے', 'دیے', 'چکا', 'ملتا', 'کبھی', 'ایسا', 'کرسکیں', 'ہوسکے', 'سکیں', 'لہذا', 'چاہئے', 'وہیں', 'اٹھایا', 'جہنوں', 'ہمارے', 'لیے', 'آرہے', 'کرگیئں', 'بنانے', 'سکتا', 'وغیرہ', 'دے', 'ہوۓ', 'رہنے', 'ہوۓ', 'کئے', 'لگے', 'لگایا', 'لائے', 'کہے', 'کرے', 'رہئں', 'آگئے', 'کئی', 'کم', 'ملی', 'جنہیں', 'ہوئیں', 'تھیں', 'ابھی', 'پاگئیں', 'آئے', 'کرا', 'دیا', 'جہاں', 'آگئیں', 'کرتی', 'رہیں', 'کرتیں', 'دیتی', 'ہوگئے', 'ديتے', 'انہں', 'ایسے', 'رکھتے', 'رہتے', 'رکھی', 'کیں', 'كیا', 'وه', 'جنہيں', 'کروائی', 'دینا', 'جسے', 'جاتی', 'اسکی', 'ملے', 'کرگئى', 'جن', 'آپکو', 'جنہوں', 'دیئے', 'والی', 'جبکہ', 'دیگر', 'آپکا', 'رکھنے', 'انہىں', 'کيے', 'یعنی', 'كيے', 'بننے', 'جاملے', 'ليكن', 'كرنے', 'كر', 'آيا', 'كرگئى', 'پھر', 'کچھ', 'آتے', 'دینے', 'اپ', 'ہونا', 'انہیں', 'لگی', 'آنے', 'کرلی', 'ہوگئى', 'پایا', 'آپکے', 'بنائی', 'کرديا', 'لا', 'رکهنے', 'كہ', 'بنا', 'كرديا', 'ركھى', 'ميں', 'ركھتے', 'كروائى', 'حتی', 'لایا', 'لیتے', 'ہمیں', 'گئى', 'بنائے', 'تاہم', 'پھر بھی', 'بنايا', 'دىے', 'ايم اے او', 'كئى', 'پڑا', 'رکھے', 'انہی', 'دیں', 'ليکر', 'البتہ', 'ہى', 'کرکے', 'پائی', 'لینا', 'دہی', 'دئیے', 'گوکہ', 'دئيے', 'كيں', 'جایا', 'کروایا', 'كیے', 'ہاں', 'کہنا', 'کیلئے', 'ہوگا', 'دیکھتے', 'آرہے', 'آگیا', 'اپنے آپ', 'طرف سے', 'ملا', 'آپكى', 'پھر بھی', 'كرگئے', 'آپکی', 'ليا', 'ديے', 'كے', 'رکھى', 'رکھتا', 'کرايا', 'چلے', 'آتا', 'لاکر', 'جیسے', 'کرليا', 'کیا ہے', 'وہاں', 'لینے', 'پاگئے', 'ہر', 'رکھنا', 'كيا', 'آیا', 'هے', 'كى', 'کرایا', 'حاصل', 'آگئى', 'دى', 'کبهی', 'جاسكتا', 'اسى', 'كی', 'كہا', 'كرو', 'اور', 'سے', 'کا', 'کى', 'سب', 'کو', 'كو', 'نے', 'اس', 'ہيں', 'پر', 'کر', 'ايک', 'كا', 'ہو', 'بهی', 'ایک', 'یہ', 'نہيں', 'ان', 'کيا', 'تو', 'وہ', 'لئے', 'کرنے', 'آپ', 'کہا', 'گيا', 'جو', 'گا', 'ہی', 'جائے', 'نہ', 'جب', 'اپنے', 'جس', 'دیا', 'ہوئے', 'تک', 'بعد', 'انہوں', 'رہے', 'ليکن', 'گی', 'کریں', 'گے', 'کرتے', 'ہونے', 'گئے', 'اپنی', 'والے', 'بہت', 'کسی', 'جا', 'تهی', 'یا', 'گئی', 'ہم', 'ہوں', 'کيلئے', 'زیادہ', 'رہا', 'طرح', 'اگر', 'اب', 'ہوا', 'دی', 'ہوتا', 'کام', 'جب', 'جو', 'گا', 'لیکن ', 'کرتى ', 'کرگئی ', 'گیا ', 'اسی', 'کیا', 'ہوئی', 'انہيں', 'جانا', 'جانے ', 'ہوئی ', 'کرگئے ', 'دیا', 'کو ', 'میں', 'ہوئے', 'ایک', 'تھے ', 'آپ ', 'نہیں', 'لیکن', 'تھی', 'جو', 'اور', 'کرتى', 'کرتا', 'کرگئی', 'کر', 'جاتے', 'لئے', 'گیا', 'کہا ', 'جاتا', 'اس ', 'جاتى', 'کرنا', 'کسی', 'بھی', 'طرف', 'ہوتا', 'لیکن', 'یہ', 'ہی', 'یا', 'اگرچہ', 'کہ', 'نے', 'رکھو', 'کرو', 'جانے', 'انہيں ', 'ديا', 'سے', 'کرگئے', 'پر', 'ہوئى', 'ان', 'اپنى', 'اپنا', 'ذریعے', 'رکھا', 'ہونے', 'اپنے', 'بعد', 'پاگئى', 'دیتے', 'كرتے', 'ہوتى', 'کہتے', 'دی', 'کرگئیں', 'اسے', 'اسی', 'لیا', 'لے', 'لی', 'کس', 'کسی', 'لیے', 'آئی', 'بنے', 'کچھ ', 'ہی', 'کرتی', 'کرتا', 'لئے', 'طور', 'نہیں', 'بلکہ', 'کیونکہ', 'کیوں', 'جس ', 'گئی', 'ہونے', 'وجہ', 'ہوگیا', 'لينے']

# BERTopic Training

In [ ]:
#create custom embedding
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
embeddings = model.encode(documents, show_progress_bar=True)
print(embeddings)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.09k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

[[-0.14562157  0.12676856 -0.25911704 ... -0.08738136 -0.13059202
   0.23454961]
 [ 0.04244933  0.06325082  0.15818478 ...  0.18492761  0.09699746
   0.00209925]
 [-0.03406477  0.27974227  0.23134182 ... -0.04284064  0.0348863
   0.25003275]
 ...
 [-0.12654519 -0.01108428 -0.15280664 ...  0.11761579  0.17626058
  -0.04933152]
 [-0.00931564 -0.09762228  0.23743257 ... -0.0712635   0.12250552
   0.09448026]
 [ 0.03949545  0.10941717  0.04547139 ...  0.04623723 -0.0348675
   0.18558027]]

In [ ]:
#pass vectorizer_model to bertopic for stopwords removal
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words= stopwords_ur)

In [ ]:
#ClassTfidf for top words
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=True)

In [ ]:
#UMAP for dimention reduction
from umap import UMAP
dim_model = UMAP(n_neighbors=15, n_components=2, random_state=42)

In [ ]:
# # #KMeans used for clustering
from sklearn.cluster import KMeans

cluster_model = KMeans(n_clusters=7, random_state=42)

In [ ]:
# from sklearn.cluster import AgglomerativeClustering

# cluster_model = AgglomerativeClustering(n_clusters=7)

In [ ]:
np.random.seed(42)

In [ ]:
topic_model = BERTopic(language="urdu", low_memory=True ,calculate_probabilities=True, vectorizer_model=vectorizer_model, top_n_words=10,hdbscan_model=cluster_model, umap_model=dim_model,ctfidf_model=ctfidf_model, verbose=True)

In [ ]:
#Fit documents in bertopic
topics, probs = topic_model.fit_transform(documents,embeddings)

2024-02-04 06:06:07,622 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-02-04 06:06:24,553 - BERTopic - Dimensionality - Completed ✓
2024-02-04 06:06:24,555 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-02-04 06:06:24,655 - BERTopic - Cluster - Completed ✓
2024-02-04 06:06:24,668 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-02-04 06:06:24,907 - BERTopic - Representation - Completed ✓

In [ ]:
print(probs)

None

In [ ]:
#topics that assign to each document
print(topics)

[2, 1, 2, 1, 3, 3, 1, 3, 3, 2, 2, 2, 3, 2, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 0, 3, 2, 2, 3, 2, 3, 3, 2, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 3, 1, 1, 2, 3, 3, 3, 2, 3, 6, 6, 2, 2, 6, 1, 6, 6, 6, 6, 2, 2, 3, 6, 6, 6, 6, 6, 6, 6, 2, 6, 6, 1, 1, 6, 2, 3, 6, 6, 6, 6, 6, 6, 2, 6, 6, 2, 1, 2, 3, 2, 2, 2, 2, 6, 2, 6, 2, 2, 6, 2, 2, 6, 6, 6, 6, 1, 6, 3, 0, 1, 1, 1, 1, 4, 1, 5, 1, 3, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 4, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 4, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 2, 5, 5, 2, 5, 2, 0, 5, 2, 5, 5, 5, 0, 5, 5, 5, 2, 1, 5, 2, 5, 0, 5, 1, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 4, 3, 4, 4, 3, 2, 2, 4, 0, 4, 4, 4, 2, 6, 4, 4, 2, 4, 3, 2, 2, 2, 4, 4, 4, 3, 4, 0, 4, 2, 3, 6, 3, 4, 3, 4, 2, 2, 0, 3, 6, 4, 4, 4, 4, 2, 2, 4, 2, 3, 2, 3, 2, 4, 0, 2, 6, 4, 3, 4, 4, 2, 4, 4, 5, 3, 0, 2, 4, 4, 0, 6, 4, 4, 3, 4, 0, 4, 5, 0, 5, 0, 4, 4, 0, 4, 4, 4, 5, 0, 5, 0, 3, 4, 0, 6, 4, 4, 4, 0, 4, 1, 4, 4, 3, 5, 0, 4, 4, 3, 0, 4, 3, 0, 1]

In [ ]:
topic_model.get_topic_freq()

   Topic  Count
3      0     78
1      1     63
0      2     62
2      3     57
5      4     54
6      5     45
4      6     40

In [ ]:
document_topics = topic_model.get_topics()

In [ ]:
#topics with score
print(document_topics)

{0: [('فلم', 0.44275789558846906), ('اداکارہ', 0.38408422310038665), ('اداکار', 0.36712812193421746), ('ویڈیو', 0.3352164085815292), ('میڈیا', 0.31514861236356934), ('بھارتی', 0.3139812173173525), ('شادی', 0.30639769915328513), ('بالی', 0.3044453528967237), ('بیٹے', 0.3043840025651749), ('خاتون', 0.3018150768631854)], 1: [('عمران', 0.40261386887901424), ('خان', 0.39929043941504994), ('حکومت', 0.37370932935342094), ('الیکشن', 0.3567845509945814), ('وزیراعظم', 0.351768415430834), ('شریف', 0.34605147160805516), ('لیگ', 0.3403391620121665), ('تحریک', 0.3346533186376195), ('نواز', 0.3231909597489307), ('کوئی', 0.3094353924381431)], 2: [('پی', 0.3325399968829313), ('ٹی', 0.32982045362943463), ('سی', 0.3235533314582003), ('پاکستان', 0.31785546220971544), ('ڈاکٹر', 0.30404252847725094), ('صحت', 0.2946258697601218), ('چیمبر', 0.28423365693459646), ('پنجاب', 0.27816860660382553), ('کمیٹی', 0.27735762290925636), ('بزنس', 0.2699486100057828)], 3: [('روپے', 0.49436267814746204), ('بک', 0.42292188820795684), ('کمی', 0.4198333178980579), ('مالی', 0.4181658665622745), ('فیس', 0.41805663524523345), ('ڈالر', 0.4161105154674892), ('فروخت', 0.396044429439956), ('فروری', 0.39296198644003966), ('سال', 0.38769165232084213), ('ملین', 0.3836761753149284)], 4: [('فون', 0.4326509103989922), ('ویوو', 0.38115239780000804), ('اسمارٹ', 0.36055972275456866), ('صارفین', 0.34016125961697874), ('سمارٹ', 0.3396049105705778), ('ٹیکنالوجی', 0.3212062113925544), ('ملازمین', 0.3153152435749545), ('کار', 0.3042272927944517), ('استعمال', 0.3030357870913949), ('ساتھ', 0.3009138142043673)], 5: [('ٹیم', 0.47681866083871205), ('میچ', 0.45169156679025974), ('ٹورنامنٹ', 0.44331349046407126), ('ہاکی', 0.43831411603711135), ('کرکٹ', 0.41300573755785963), ('کپتان', 0.38410786491114235), ('کھلاڑیوں', 0.38274881907943775), ('کپ', 0.37755364121501406), ('بابر', 0.3751903369512691), ('سیریز', 0.3721051988562702)], 6: [('کورونا', 0.6361415020516241), ('وائرس', 0.5800492691910772), ('ویکسین', 0.4864624659676426), ('ہیلتھ', 0.46875857952052247), ('گھنٹوں', 0.4649413977611015), ('کیسز', 0.4427697282894312), ('ہزار', 0.43735875405508456), ('مریض', 0.42035484881013374), ('سنٹر', 0.41063252440033254), ('ٹیسٹ', 0.3989091925130532)]}

In [ ]:
#shows which documents assign to specific topic
topic_model.get_representative_docs(topic=None)

{0: [' ہدایت کار کامران شاہد کی نئی پاکستانی فلم ہوئے تم اجنبی کے شاندار میوزک کی تعارفی تقریب کا اہتمام کراچی کے مقامی سینماء گھر میں کیا گیا جس میں شوبز کے چمکتے ستاروں سمیت اہم سیاسی شخصیات اور شخصیات نے بڑی تعداد میں شرکت کی۔اس موقع پر باصلاحیت ہدایت کار اور سکرپٹ رائٹر کامران شاہد کے علاوہ اداکار سہیل احمد  علی خان شمعون عباسی محمود اسلم فیصل قریشی جاوید شیخ اور فلم کے ہیرو میکال ذوالفقار بھی موجود تھے۔ میڈیا وال پر موجود فوٹوگرافرز اور کیمرہ مین اپنے کیمروں کے ذریعے ان کی تصاویر اور ویڈیوز بناتے نظر آرہے تھے۔بین الاقوامی شہرت یافتہ گلوکار علی ظفر کا گایا ہوا فلم کا ٹائٹل سونگ ہوئے تم اجنبی کی ویڈیو حاضرین کو دکھائی گئی ۔بین الاقوامی شہرت یافتہ بانسری کے ماہر اور میوزک کمپوزر باقر عباس کے کمپوز کردہ اس گانے کو علی ظفر جیسے شاندار گلوکار نے اپنی سریلی آواز میں پیش کیا۔ٹائٹل گانے کی ویڈیو کے بعد فلم کی منٹ کی جھلکیاں پیش کی گئیں جس میں فلم کے دلچسپ سین کے ساتھ ساتھ دو مزید گانوں کی جھلکیاں بھی شامل تھیں۔ اس رومانوی داستان میں صوفیانہ موسیقی کی ملکہ عابدہ پروین باقر عباس ساحر علی بگا نجات اور نوید ناشاد جیسے لیجنڈز کی دل کو چھو لینے والی موسیقی کے  شاہکار گیت پیش کیے گئے۔ علی ظفر کے علاوہ عابدہ پروین اور عاصم اظہر نے فلم میں اپنی آواز کا جادو جگایا ہے۔ فلم کی جھلکیوں کے بعد ہال کے ریڈ کارپٹ ایریا میں فلم کے نمایاں ستارے اور دیگر عملہ میڈیا کی جانب سے کیے گئے سوالوں کے جواب دینے کے لیے موجود تھا۔شاہد فلمز کی پروڈیوس کردہ ستاروں سے سجی محبت بھری یہ رومانوی داستان پاکستان اور بھارت کے درمیان  کے منفرد اور تاریخی پس منظر میں فلمائی گئی ہے۔ اس فلم میں میکال ذوالفقار کے مقابل سعدیہ خان مرکزی کردار ادا کررہی ہیں جب کہ دیگر تجربہ کار ستاروں میں شفقت چیمہ ثمینہ پیرزادہ عائشہ عمر عدنان جیلانی اور ماضی کے ہیرو شاہد شامل ہیں۔تقریب میں جاوید شیخ خوش بخت شجاعت سابق گورنر محمد زبیر مظہر عباس کامران خان اور دیگر نے فلم کی تعریف کرتے ہوئے کامران شاہد کی کاوشوں کو سراہا۔',
  'رانا شمیم کے بیٹے احمد حسن رانا عدالت میں کونسی ویڈیو چلانا چاہتے تھے حقیقت سامنے آگئیاپنے پروگرام میں ڈاکٹر شاہد مسعود نے دعویٰ کیا کہ سابق جج رانا شمیم کے صاحبزادےعدالت میں ایک لیپ ٹاپ لیکر آئے تھے اس لیپ ٹاپ میں کیا تھا اس لیپ ٹاپ میں ایک فلم ہے جو انہوں نے کہا کہ میں عدالت میں چلانا چاہتا ہوں لیکن جسٹس اطہرمن اللہ نے کہا کہ نہیں آپ نہیں چلاسکتے۔ ڈاکٹر شاہد مسعود نے دعویٰ کیا کہ رانا شمیم کے بیٹے جو فلم چلانا چاہتے تھے اس فلم کی ایک سے زیادہ کاپی ہیں میں زیادہ بات نہیں کرنا چاہتا لیکن کہاں ایسے دائیں بائیں موڑ لے گی۔ڈاکٹرشاہد مسعود نے مزید دعویٰ کیا کہ ثاقب نثار سے متعلق ایک دو خبریں اور چھپنے والی ہیں میں نہیں چھاپ رہا اخبارات میں خبریں آنیوالی ہیں اسلئے نظر رکھیں اور جاگتے رہیں۔ڈاکٹر شاہد مسعود کا دعویٰ ہے کہ رانا شمیم کے بیٹے ایک لیپ ٹاپ لیکر آئے تھے جبکہ حقیقت یہ تھی کہ وہ عدالتی عملے سے ویڈیو چلانے کیلئے لیپ ٹاپ مانگ رہے تھےاس ویڈیو کو لیکر غریدہ فاروقی نے بھی ٹویٹ کیا کہ ایک اور ویڈیو آگئی رانا شمیم کے بیٹے نے ویڈیو چلانے کی اجازت مانگ لی اور عدالت نے کہا کہ ہم ایک ویڈیو چلانا چاہتے ہیں  لیپ ٹاپ لاسکتے ہیں۔اپنے پروگرام میں ڈاکٹر شاہد مسعود نے دعویٰ کیا کہ سابق جج رانا شمیم کے صاحبزادےعدالت میں ایک لیپ ٹاپ لیکر آئے تھے اس لیپ ٹاپ میں کیا تھا اس لیپ ٹاپ میں ایک فلم ہے جو انہوں نے کہا کہ میں عدالت میں چلانا چاہتا ہوں لیکن جسٹس اطہرمن اللہ نے کہا کہ نہیں آپ نہیں چلاسکتے۔ ڈاکٹر شاہد مسعود نے دعویٰ کیا کہ رانا شمیم کے بیٹے جو فلم چلانا چاہتے تھے اس فلم کی ایک سے زیادہ کاپی ہیں میں زیادہ بات نہیں کرنا چاہتا لیکن کہاں ایسے دائیں بائیں موڑ لے گی۔ڈاکٹرشاہد مسعود نے مزید دعویٰ کیا کہ ثاقب نثار سے متعلق ایک دو خبریں اور چھپنے والی ہیں میں نہیں چھاپ رہا اخبارات میں خبریں آنیوالی ہیں اسلئے نظر رکھیں اور جاگتے رہیں۔سوال یہ ہیں کہ اس لیپ ٹاپ میں ایسی کونسی فلم تھی جوجسٹس اطہر من اللہ نے چلانے نہیں دی اسکا بھانڈا سابق جج کے بیٹے نے پھوڑدیاسماء ٹی وی کے پروگرام میں جج راناشمیم کے بیٹے احمد حسن رانا نے بتایا کہ جو وہ ویڈیو چلانا چاہتے تھے اس ویڈیو میں ایسا کیا تھا دراصل وہ ویڈیو فیصل واڈا کی تھی اور فیصل واڈا کا بیان تھا جو انہوں نے منصور علی خان کے شو میں دیا۔رانا شمیم کے بیٹے کا کہنا تھا کہ میں عدالت کو فیصل واڈا کی ویڈیو دکھانا چاہتا تھا انہوں نے میرے والد کے بارے میں اول فول بکا تھا اور مجھ پر جھوٹے الزامات لگائے تھے میں چاہتا تھا کہ عدالت فیصل واڈا کو بھی طلب کرےان کا کہنا تھا کہ فیصل واڈا نے مجھ پر اور میرےو الد پر الزامات لگائے تھے انکے اپنے حقائق کلئیر نہیں تھے۔فیصل واڈا کی یہ ویڈیو منصور علی خان کے شو کی تھی اس کلپ میں فیصل واڈا نے کہا تھا کہ ان کا منہ کالا کرکے انہیں لٹکا کر لتر ماریں یہ پاکستان کو افراتفری کی طرف لے جانا چاہتے ہیں انکے ضمیر پیسے کی وجہ سے جاگتے ہیں۔فیصل واڈا نے سابق جج کو بے شرم اور بے حیا قرار دیتے ہوئے کہا تھا کہ یہ بے شرم بے حیاء دوسروں کو فائدہ دیتے ہیں اور ضمیر جاگنے کی بات کرتے ہیں یہ جج بھگوڑا ہے۔نہ صرف فیصل واڈا نے سخت زبان استعمال کی بلکہ یہ الزام بھی لگایا کہ راناشمیم کے بیٹے کو میرٹ سے ہٹ کر ایڈوکیٹ جنرل لگایا گیادیکھئےو ہ ویڈیو جس کے بارے میں مختلف قیاس آرائیاں کی گئیںسوال یہ ہیں کہ اس لیپ ٹاپ میں ایسی کونسی فلم تھی جوجسٹس اطہر من اللہ نے چلانے نہیں دی اسکا بھانڈا سابق جج کے بیٹے نے پھوڑدیاسماء ٹی وی کے پروگرام میں جج راناشمیم کے بیٹے احمد حسن رانا نے بتایا کہ جو وہ ویڈیو چلانا چاہتے تھے اس ویڈیو میں ایسا کیا تھا دراصل وہ ویڈیو فیصل واڈا کی تھی اور فیصل واڈا کا بیان تھا جو انہوں نے نجی چینل کے شو میں دیا۔رانا شمیم کے بیٹے کا کہنا تھا کہ میں عدالت کو فیصل واڈا کی ویڈیو دکھانا چاہتا تھا انہوں نے میرے والد کے بارے میں اول فول بکا تھا اور مجھ پر جھوٹے الزامات لگائے تھے میں چاہتا تھا کہ عدالت فیصل واڈا کو بھی طلب کرےان کا کہنا تھا کہ فیصل واڈا نے مجھ پر اور میرےو الد پر الزامات لگائے تھے انکے اپنے حقائق کلئیر نہیں تھے۔فیصل واڈا کی یہ ویڈیو نجی چینل کے شو کی تھی اس کلپ میں فیصل واڈا نے کہا تھا کہ ان کا منہ کالا کرکے انہیں لٹکا کر لتر ماریں یہ پاکستان کو افراتفری کی طرف لے جانا چاہتے ہیں انکے ضمیر پیسے کی وجہ سے جاگتے ہیں۔فیصل واڈا نے سابق جج کو بے شرم اور بے حیا قرار دیتے ہوئے کہا تھا کہ یہ بے شرم بے حیاء دوسروں کو فائدہ دیتے ہیں اور ضمیر جاگنے کی بات کرتے ہیں یہ جج بھگوڑا ہے۔نہ صرف فیصل واڈا نے سخت زبان استعمال کی بلکہ یہ الزام بھی لگایا کہ راناشمیم کے بیٹے کو میرٹ سے ہٹ کر ایڈوکیٹ جنرل لگایا گیادیکھئےو ہ ویڈیو جس کے بارے میں مختلف قیاس آرائیاں کی گئیں',
  'لکی مروت کے علاقے شاہ حسن خیل میں والی بال ایک مقبول کھیل تھا نوجوان اس کھیل کے اتنے شوقین تھے کہ جب بھی  ٹیموں کے درمیان میچ ہوتا تو گراؤنڈ تماشائیوں سے کھچا کھچ بھرا ہوتا لیکن ایک افسوسناک واقعے نے اس گاؤں سے والی بال جیسے کھیل کا تقریبا خاتمہ کردیا۔یکم جنوری  کو شاہ حسن خیل میں ایک انتہائی افسوسناک واقعہ پیش آیا جہاں والی بال میچ کے دوران خودکش کار بم دھماکے میں  سے زائد افراد جاں بحق دو سو کے قریب زخمی ہو گئے ۔یہ واقعہ یکم جنوری کو تقریباً  بجے گاؤں شاہ حسن خیل میں پیش آیا جب دو مقامی ٹیموں کے مابین میچ جاری تھا کہ اچانک زور دار دھماکہ ہوا عینی شاہدین کے مطابق خودکش بمبار نے بارود سے بھری ڈبل ڈور کیبن کھیل کے میدان کے ساتھ بنی دیوار کے ساتھ ٹکرا دی مذکورہ میدان گھروں کے بیچ واقع ہے اور دھماکے سے آس پاس کے مکانات اور دوکانوں کو بھی شدید نقصان پہنچا۔میدان میں موجود  کھلاڑیوں میں سے صرف ایک کھلاڑی اور ریفری عبدالرحمان زندہ بچ سکے۔ عبدالر حمان کی گردن پیشانی اور جسم کے دیگر حصوں پر زخم آئے۔ سماعت اور بینائی بری طرح متاثر ہوئی۔ ایک کھلاڑی بچ گیا وہ نیٹ مین کے طور پر کھیل رہا تھا وہ جو کھیل کے دوران نیٹ کے قریب کھڑا ہونے کی وجہ سے بچ گیا۔اس افسوس ناک واقعے کو  سال ہوچکے ہیں لیکن والی بال کا کھیل آج تک اس علاقے میں دہشت کی علامت بنا ہوا تھا ۔اس کھیل پر علاقے کے لوگ جان چھڑکتے تھے وہ اسی کھیل سے بھاگنے لگے۔بعض لوگوں کے مطابق انھیں اس کھیل سے ہی نفرت ہو گئی اور کسی کا کہنا ہے کہ اس کھیل سے ان کے زخم تازہ ہو جاتے ہیں۔ اس میدان اور اس کے قریب تباہ ہونے والے مکانات کا ملبہ آج بھی وہیں موجود ہے اس میدان میں صرف ایک تبدیلی آئی ہے۔ جس جانب سے گاڑی میدان میں داخل ہوئی تھی اس جانب دیوار کھڑی کر دی گئی ہے ۔لکی مروت اور اس کے قریب واقع سینکڑوں چھوٹے بڑے دیہاتوں میں والی بال سب سے پسندیدہ کھیل رہا ہے۔ یہاں سے والی بال کے کھلاڑی قومی اور محکمانہ ٹیموں میں بھی کھیل چکے ہیں۔اس واقعے سے متاثرہ میچ ریفری عبدالرحمان کے ذہن پر آج بھی یہ واقعہ نقش ہے جس کا کہنا ہے کہ میں یہاں عصر کے وقت آتا تھا اور ریفری کے فرائض سر انجام دیتا تھا۔عبدالرحمان کا کہنا تھا کہ دھماکے کے بعد جو منظر میں نے دیکھا وہ دیکھنے کے قابل نہیں تھا ہرطرف اندھیرا تھا۔ دھماکے کے بعد میں بے ہوش ہوگیا تھا اور جب ہوش آیا تو میرے پیشانی پر لگے زخم سے خون بہہ رہا تھا۔ اردگرد لاشیں اور زخمی پڑے تھے اور لوگ درد سے کراہ رہے تھے۔ عبدالرحمان کے مطابق اس واقعے میں اس نے اپنے بڑے بھائی اور  پڑوسیوں کو کھودیا تھا گاؤں میں تقریبا ہر گھر میں کسی نہ کسی رشتہ دار کی موت ہوئی تھی۔اسکے مطابق اس واقعے کا صدمہ اتنا بڑا تھا کہ تقریباً  سالوں تک کسی نے علاقے میں اس کھیل کو کھیلنے کی مت نہیں کی اور دوسرا س واقعے میں گاوں کے اکثر نوجوان جو والی بال کھیلتے تھے جان سے چلے گئے تھے۔ایک سماجی کارکن عبدالقدوس خان جو حال ہی میں شاہ حسن خیل کی ویلج کونسل کے چیئرمین منتخب ہوئے ہیں علاقے میں اس کھیل کو دوبارہ متعارف کرانے کی کوشش کر رہے ہیں۔ عبدالقدوس خان کا کہنا ہے کہ والی بال ہمارا پسندیدہ کھیل ہے  گاؤں کے نوجوانوں کو ایک بار پھر اس کھیل کو اپنانے کے لیے قائل کیا انکے مطابق والی بال گاؤں میں مقبول ہے کیونکہ یہاں کرکٹ اور فٹ بال کے لیے کوئی میدان نہیں ہے۔انہوں نے تحریک انصاف کی صوبائی حکومت سے والی بال کیلئے سہولیات کا بھی مطالبہ کیا اور کہا کہ اگر اس علاقے کو سہولیات اور جدید گراؤنڈ دیا جائے تو قومی سطح کے کھلاڑی پیدا ہوں گے۔'],
 1: ['کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بیٹھ کر شریف خاندان کے ایماء پر بیان حلفی دیا بیان حلفی کو لیکر سوشل میڈیا پر اہم سوالات اٹھ گئے۔وزیراعظم کے ترجمان ڈاکٹر شہبازگل کا کہنا ہے کہ سابق چیف جسٹس کا بیان لندن سے نوٹرائز ہوا ہے۔ڈاکٹر شہباز گل نے اس پر کہا کہ حالات چیک کر لیں زرا بھگوڑے مجرم کو بچانے کی کوشش کرنے والے شمیم صاحب کا بیان حلفی بھی لندن سے نوٹرائزڈ ہوا ہے ۔شہباز گل نے سوال کیا کہ کیا شمیم صاحب نواز شریف کے خرچے پر لندن میں رہائش پذیر ہیں   لیگ کے حامی سمجھے جانیوالے صحافی اظہر جاوید کا کہنا تھا کہ سابق چیف جج رانا شمیم کا بیان حلفی انہوں نے یہ بیان لندن میں دس نومبر کو اوتھ کمشنر نوٹری پبلک کے سامنے ریکارڈ کروایا یہ حلفیہ بیان برطانوی قوانین کے مطابق مصدقہ دستاویز اور کسی بھی عدالت میں قابل قبول ہے  لیگ کے ایک اور حامی سمجھے جانیوالے صحافی نے دعویٰ کیا کہ رانا شمیم کی اہلیہ امریکا میں زیر علاج تھیں اور امریکا سے واپسی پر لندن میں قیام کے دوران سابق چیف جج نے جن لوگوں کے متعلق یہ سچ تھا انکے روبرو بیان کر کے حلفیہ اقرار کیا  حلف نامے پر سب سے پہلے سوال صحافی عدیل وڑائچ نے اٹھایا عدیل وڑائچ کا اس پر کہنا تھا کہ کیسا حسین اتفاق ہے کہ جسٹس ثاقب نثار پر الزامات لگانے والے گلگت بلتستان کے سابق چیف جسٹس نے لندن جا کر بیان حلفی دیا ہے لندن کے نوٹری پبلک کی مہر بیان حلفی پر موجود ہے  شریف اور جج رانا شمیم کے حلف نامے لندن کے چارلس گوتھری نامی ایک ہی پبلک نوٹری سے تصدیق یافتہ ہیں۔نوازشریف کے پرانے حلف نامے میں ڈیوڈ لارنس کے ذاتی معالج ہیں جس کی نوازشریف نے اگست  میں رپورٹ ارسال کی تھی جس میں کہا گیا تھا کہ کورونا کے بعد صورتحال معمول پر آنے کے بعد نواز شریف کے دل کا علاج ہونا ہے۔ڈاکٹر ڈیوڈ کی  کی رپورٹ کے مطابق نواز شریف ایک معمر شخص ہیں اور ان کا کورونا وائرس کے دنوں میں باہر نکلنا خطرے سے خالی نہیں ہے۔ اس لئے وہ نواز شریف کو لندن میں مقیم رہنے کا مشورہ دیتے ہیں تاکہ ان کا مناسب علاج ممکن بنایا جا سکے۔اس حلف نامے کی لندن سے تصدیق کی گئی ہے جسے چارلس ڈروستان گوتھری ایل ایل سی نے تصدیق کروایا اور اس کمپنی کی اس پر مختلف مہریں لگاکر تصدیق کی گئی ہے۔یہ لندن والے حلف نامہ میں جسٹس عامر فاروق کا جو ذکر کیا گیا لیکن ہم بات یہ ہے کہ الیکشن سے پہلے جو بنچ تھا اس میں جسٹس عامر فاروق شامل ہی نہیںاس پر ایک سوشل میڈیا صارف نے سوال اٹھایا کہ آخر جج صاحب کا ضمیر لندن میں ہی کیوں جاگا  حسین کا کہنا تھا کہ عام لوگوں کا ضمیر سعودی عرب میں جبکہ اشرافیہ کا لندن میں جاگتا ہے۔ سابق جسٹس رانا شمیم کا ضمیر بیقرار ہوا تو وہ لندن بھاگے اور وہاں کے نوٹری پبلک کے سامنے بیان حلفی دے دیا۔ نواز شریف کی دولت کیسے کیسے کرشمے دکھاتی ہے۔  سوشل میڈیا صارف نے لکھا کہ عمران خان اب بھگتو نوازشریف کو جانے دیا اب وہ لندن میں بیٹھا سازشیں کررہاھے سابقہ ججوں کو بلاکر کہتا ھے میرے حق میں بیان حلفی لکھ کر دو اقتدار ملا تو مالامال کردوں گا آنے والی نسلیں بھی موج کریں گی اسی کی مثال سابقہ جج شمیم بھی ھے جس نے لندن میں بیان حلفی لکھ کردیا  اور سوشل میڈیا صارف نے تبصرہ کیا کہ جج شمیم صاحب کا بیان حلفی بھی لندن سے آگیا ہے لیکن وہ پھر بھی نہیں آیا جو کی دوائی لینے گیا تھا چور داڑھی میں تنکا ضرور ہوتا ہے میاں صاحب ججوں کو استعمال کررہے ہیں۔  پر قانونی ماہرین کا کہنا تھا کہ لندن سے آیا یہ حلف نامہ بھی شریف خاندان کو ریلیف نہیں دے سکے گا سابق چیف جسٹس شمیم کو خود عدالت کے سامنے پیش ہونا ہوگا اور بیان دینا ہوگا جبکہ اسکے جواب پر ثاقب نثار اپنا دفاع پیش کریں گے۔قانونی ماہرین کے مطابق یہ بھی ممکن ہے کہ عدالت بیان حلفی دینے والے سابق چیف جسٹس سے ثبوت بھی مانگے۔ان کا مزید کہنا تھا کہ پانامہ کیس کی سماعت کے دوران شریف خاندان نے عدالت کے روبرو کئی ثبوت پیش کئے تھے جسے عدالت نے مسترد کردیا تھا  انہیں بھی نوٹری اور سفارتخانے سے تصدیق کیا گیا تھا جبکہ قطری خط بھی عدالت نے مسترد کردیا تھا۔',
  'جنگ جیو کے صحافی انصارعباسی کا کہنا ہے کہ کوئی ڈیل نہیں ہورہی اور نہ ہی مستقبل قریب میں نوازشریف واپس آرہے ہیں۔انصارعباسی نے کسی ڈیل اور نوازشریف کی ڈیل کی خبروں کو قیاس آرائی قرار دیدیا اور اپنے ذرائع کے حوالے سے لکھا کہ انکے ذرائع نے ان خبروں کی تردید کی ہے کہ کوئی ڈیل ہوگئی ہے یا پھر کسی ایسے اسکرپٹ پر عمل ہو رہا ہے جس سے نواز شریف کی لندن واپسی میں آسانی پیدا ہو سکے جہاں وہ عدالت سے اجازت ملنے کے بعد چند ماہ کیلئے اپنے علاج کیلئے گئے تھے لیکن اس کے بعد سے واپس نہیں آئے۔ان کا مزید کہنا تھا کہ نواز شریف اور اسٹیبلشمنٹ کے درمیان کوئی براہِ راست رابطہ نہیں۔ نوازشریف کیا سوچ رہے ہیں اس سے نون لیگ کی دوسری سطح کی قیادت بھی لا علم ہے اور انہیں نہیں معلوم کہ نوازشریف اُن لوگوں کے ساتھ رابطے میں ہیں جو ان کی واپسی کے حوالے سے اہم ہیں۔ن لیگی رہنما ایاز صادق سے متعلق انصارعباسی کا کہنا تھا کہ ایااز صادق کے بیانات نے لوگوں کو حیران کردیا تھا اور انکے بیانات کی وجہ سے سیاسی درجہ حرارت میں اضافہ ہوا تھا۔ایاز صادق نے کہا تھا کہ نواز شریف پاکستان آ رہے ہیں ۔انکے مطابق جب جیو کے ایک شو میں دوران انٹرویو ان سے پوچھا گیا تو انہوں نے کہا کہ مجھے نہیں معلوم کہ کیا ہونے والا ہے لیکن میرے خیال میں جلد کوئی بڑا دھماکا ہونے والا ہے۔انہوں نے کہا کہ یہ سب اچانک ہوگا اور آپ لوگوں کو یہ معاملات آہستہ آہستہ ہوتے نظر نہیں آئیں گے۔انصار عباسی کے مطابق ایازصادق نے اس بات کی تصدیق کی تھی کہ نوازشریف لندن میں ملاقاتیں کررہے ہیں اور غیرسیاسی شخصیات سے رابطے کررہے ہیں لیکن ایازصادق کو ملاقاتوں میں زیربحث معاملات اور ایجنڈا کا پتہ نہیں لیکن دوسری طرف ایاز صادق یہ بھی کہہ رہے ہیں کہ وہ لوگ نواز شریف سے ملاقات کر رہے ہیں کیونکہ انہیں احساس ہوگیا ہے کہ پی ٹی آئی کو اقتدار میں لا کر انہیں ناکامی ہوئی ہے اور وہ حکومت سے اپنے سپورٹ بھی واپس لے چکے ہیں اور نواز شریف سے ملاقات کر رہے ہیں کیونکہ نون لیگ کے پاس اپنا ووٹ بینک برقرار ہے۔انصارعباسی نے آصف زرداری کے حوالے سے ڈیل کا بھی حوالہ دیا اور کہا کہ عسکری ذریعے نے کہا تھا کہ آصف زرداری کو چاہئے کہ وہ اُس شخص کا نام بتائیں جس نے ان سے اسٹیبلشمنٹ کی طرف سے ملاقات کرکے مستقبل کے سیٹ اپ کے حوالے سے مدد مانگی ہے۔ عسکری ذریعے نے آصف زرداری کے بیانات پر اظہارافسوس بھی کیا تھا اور اسے افسوسناک اور غیرذمہ دارانہ قراردیا تھا۔سینئر صحافی کے مطابق دلچسپ امر یہ ہے کہ ایاز صادق کے بیان کو وزیراعظم عمران خان کی طرف سے بالواسطہ توثیق حاصل ہو گئی ہے ۔ وزیراعظم نے کہا تھا کہ ایسی راہیں تلاش کی جا رہی ہیں جن سے سابق وزیراعظم نواز شریف کی نا اہلیت ختم کرنے کی کوشش کی جا سکے۔ اگر مجرموں کو چھوڑا جانے لگا تو تمام جیلوں کے دروازے کھول دینا چاہئیں۔اپنے آرٹیکل میں انصار عباسی نے کہا کہ مسلم لیگ ن کے ایک با خبر ذریعے نے رابطہ کرنے پر نام ظاہر نہ کرنے کی شرط پر بتایا کہ وہ یہ نہیں بتا سکتے کہ ایاز صادق نے کس بنیاد پر انکشافات کیے ہیں۔ انہوں نے کہا کہ بالواسطہ روابط ہیں جن سے کوئی ٹھوس بات سامنے نہیں آتی یا یہ معلوم نہیں ہوتا کہ نواز شریف کیا چاہتے ہیں۔اپنے ایک ویڈیو لاگ بھی انصار عباسی نے اس پر تبصرہ کیا تھا اور کہا تھا کہ وزیراعظم حیران ہیں پریشان ہیں یا گھبرائے ہوئے ہیں اسکا فیصلہ کوئی بھی کرسکتا ہے ان الفاظ کا جائزہ لیں تو ایسے لگتا ہے کہ نوازشریف کی نااہلی ختم ہونے جارہی ہے انہیں کرپشن کیسز میں بے گناہ قراردیا جارہا ہے اور ان پر وزیراعظم ہاؤس کے دروازے کھولے جارہے ہیں جس کا مطلب چوتھی بار انکا وزیراعظم بننا ہے۔انصار عباسی نے یہ بھی سوال اٹھایا تھا کہ وزیراعظم کا اشارہ کس کی طرف ہے کون وزیراعظم کی نااہلی ختم کروانے کی کوشش کررہا ہے اس بارے انہیں وضاحت کرنی چاہئے۔انصار عباسی کی خبر کے بعد سوال یہ اٹھتا ہے کہ کیا ایازصادق لندن سیرسپاٹے کرکے اور اپنے لیڈر کادیدار کرکے واپس آگئے ہیں ایازصادق نے یہ کیوں کہا کہ آئندہ چند روز میں بڑا دھماکہ ہونیوالا ہے ایاز صادق کے ان بیانات پر پاکستانی میڈیا نے یہ تاثر دیا کہ جیسے اسٹیبلشمنٹ اور نوازشریف کی ڈیل آخری مراحل میں ہے اور وہ نہ صرف وطن واپس آئیں گے بلکہ ان پر نااہلی اور سزا کے کیسز ختم ہوجائیں گے۔',

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,78,0_فلم_اداکارہ_اداکار_ویڈیو,"[فلم, اداکارہ, اداکار, ویڈیو, میڈیا, بھارتی, ش...",[ ہدایت کار کامران شاہد کی نئی پاکستانی فلم ہو...
1,1,63,1_عمران_خان_حکومت_الیکشن,"[عمران, خان, حکومت, الیکشن, وزیراعظم, شریف, لی...",[کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بی...
2,2,62,2_پی_ٹی_سی_پاکستان,"[پی, ٹی, سی, پاکستان, ڈاکٹر, صحت, چیمبر, پنجاب...",[کراچی گوگل کے نیکسٹ بلین یوزرز اقدام کے تحت ...
3,3,57,3_روپے_بک_کمی_مالی,"[روپے, بک, کمی, مالی, فیس, ڈالر, فروخت, فروری,...",[اسلام آباد ریاستہائے متحدہ امریکہ کوویکس کے ...
4,4,54,4_فون_ویوو_اسمارٹ_صارفین,"[فون, ویوو, اسمارٹ, صارفین, سمارٹ, ٹیکنالوجی, ...",[لاہور نے اپنے پہلے اسمارٹ فون کی رونمائی کر د...
5,5,45,5_ٹیم_میچ_ٹورنامنٹ_ہاکی,"[ٹیم, میچ, ٹورنامنٹ, ہاکی, کرکٹ, کپتان, کھلاڑی...",[ نگران وزیراعلی پنجاب سید محسن نقوی کی ہدایت ...
6,6,40,6_کورونا_وائرس_ویکسین_ہیلتھ,"[کورونا, وائرس, ویکسین, ہیلتھ, گھنٹوں, کیسز, ہ...",[ ضلع فیصل آبادکے کوروناویکسی نیشن سنٹرز پراب ...

In [ ]:
topic_model.get_document_info(documents)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document
0,انٹلیکچوئل پراپرٹی رائٹس آرگنائزیشن کے چیئرم...,2,2_پی_ٹی_سی_پاکستان,"[پی, ٹی, سی, پاکستان, ڈاکٹر, صحت, چیمبر, پنجاب...",[کراچی گوگل کے نیکسٹ بلین یوزرز اقدام کے تحت ...,پی - ٹی - سی - پاکستان - ڈاکٹر - صحت - چیمبر -...,False
1,سٹیٹ بینک پارلیمنٹ کے ایوان بالا سینیٹ کی گول...,1,1_عمران_خان_حکومت_الیکشن,"[عمران, خان, حکومت, الیکشن, وزیراعظم, شریف, لی...",[کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بی...,عمران - خان - حکومت - الیکشن - وزیراعظم - شریف...,False
2,ڈپٹی کمشنر کمانڈنٹ دیر لیویز افتخار احمد اور ...,2,2_پی_ٹی_سی_پاکستان,"[پی, ٹی, سی, پاکستان, ڈاکٹر, صحت, چیمبر, پنجاب...",[کراچی گوگل کے نیکسٹ بلین یوزرز اقدام کے تحت ...,پی - ٹی - سی - پاکستان - ڈاکٹر - صحت - چیمبر -...,False
3,سیالکوٹ چیمبر آف کامرس کے سینئر نائب صدر وہب ...,1,1_عمران_خان_حکومت_الیکشن,"[عمران, خان, حکومت, الیکشن, وزیراعظم, شریف, لی...",[کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بی...,عمران - خان - حکومت - الیکشن - وزیراعظم - شریف...,False
4,جاپان کی کار ساز کمپنی ٹویوٹا نے کہا ہے کہ وہ...,3,3_روپے_بک_کمی_مالی,"[روپے, بک, کمی, مالی, فیس, ڈالر, فروخت, فروری,...",[اسلام آباد ریاستہائے متحدہ امریکہ کوویکس کے ...,روپے - بک - کمی - مالی - فیس - ڈالر - فروخت - ...,False
...,...,...,...,...,...,...,...
394,بولیویا کے تین لڑکے اس وقت ہسپتال پہنچ گئے جب...,0,0_فلم_اداکارہ_اداکار_ویڈیو,"[فلم, اداکارہ, اداکار, ویڈیو, میڈیا, بھارتی, ش...",[ ہدایت کار کامران شاہد کی نئی پاکستانی فلم ہو...,فلم - اداکارہ - اداکار - ویڈیو - میڈیا - بھارت...,False
395,ٹوکیو کے شن اوبوکو مضافات میں ایک ایسا انوکھا ...,4,4_فون_ویوو_اسمارٹ_صارفین,"[فون, ویوو, اسمارٹ, صارفین, سمارٹ, ٹیکنالوجی, ...",[لاہور نے اپنے پہلے اسمارٹ فون کی رونمائی کر د...,فون - ویوو - اسمارٹ - صارفین - سمارٹ - ٹیکنالو...,False
396,آسٹریلیا کی ایک پیزا شاپ نے آسٹریلوی فائرفائٹ...,3,3_روپے_بک_کمی_مالی,"[روپے, بک, کمی, مالی, فیس, ڈالر, فروخت, فروری,...",[اسلام آباد ریاستہائے متحدہ امریکہ کوویکس کے ...,روپے - بک - کمی - مالی - فیس - ڈالر - فروخت - ...,False
397,دہلی کے لوک نائیک ہسپتال کے ایک بستر پر ماہ ...,0,0_فلم_اداکارہ_اداکار_ویڈیو,"[فلم, اداکارہ, اداکار, ویڈیو, میڈیا, بھارتی, ش...",[ ہدایت کار کامران شاہد کی نئی پاکستانی فلم ہو...,فلم - اداکارہ - اداکار - ویڈیو - میڈیا - بھارت...,False
398,منیلا فلپائن کے الیکشن حکام نے جمعے کو ہونے و...,1,1_عمران_خان_حکومت_الیکشن,"[عمران, خان, حکومت, الیکشن, وزیراعظم, شریف, لی...",[کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بی...,عمران - خان - حکومت - الیکشن - وزیراعظم - شریف...,False

In [ ]:
topic_distr, _ = topic_model.approximate_distribution(documents, window=3, min_similarity=0.01)

100%|██████████| 1/1 [00:00<00:00,  1.47it/s]

In [ ]:
print(topic_distr)

[[0.10215937 0.15652699 0.32228055 ... 0.09780149 0.09355867 0.1096797 ]
 [0.1117398  0.27715831 0.14734692 ... 0.10775771 0.11725155 0.09284228]
 [0.11217489 0.17139389 0.308853   ... 0.09787739 0.09151896 0.11869382]
 ...
 [0.10612152 0.09075082 0.12305417 ... 0.12415329 0.11247949 0.10194984]
 [0.34220481 0.096599   0.1200349  ... 0.15068059 0.10749395 0.10213763]
 [0.09168212 0.37417868 0.09674426 ... 0.12780244 0.14242597 0.07910225]]

In [ ]:
topic_model.visualize_distribution(topic_distr[0], width=600,height=600, title="Topic Probability Distributio(UNTM)")

# Evaluation
we used three evaluation metrics to compare the results.

1. The coherence score is used to capture the degree of similarity between the words within each topic, with higher scores indicating more coherent topics. We used two coherence metrics NPMI and Cv Score.
2. IRBO measures are used to assess how different and distinct the topics are in a topic model.

### Coherence Score
To evaluate the model topics coherence we use [Gensim](https://radimrehurek.com/gensim/models/coherencemodel.html) library

In [ ]:
texts = [[word for word in str(document).split() if word not in stopwords_ur] for document in documents]
id2word = corpora.Dictionary(texts)
corpus = [id2word.doc2bow(text) for text in texts]

In [ ]:
topics_bert=[]
for i in topic_model.get_topics():
  row=[]
  topic= topic_model.get_topic(i)
  for word in topic:
     row.append(word[0])
  topics_bert.append(row)

In [ ]:
print(topics_bert)

[['فلم', 'اداکارہ', 'اداکار', 'ویڈیو', 'میڈیا', 'بھارتی', 'شادی', 'بالی', 'بیٹے', 'خاتون'], ['عمران', 'خان', 'حکومت', 'الیکشن', 'وزیراعظم', 'شریف', 'لیگ', 'تحریک', 'نواز', 'کوئی'], ['پی', 'ٹی', 'سی', 'پاکستان', 'ڈاکٹر', 'صحت', 'چیمبر', 'پنجاب', 'کمیٹی', 'بزنس'], ['روپے', 'بک', 'کمی', 'مالی', 'فیس', 'ڈالر', 'فروخت', 'فروری', 'سال', 'ملین'], ['فون', 'ویوو', 'اسمارٹ', 'صارفین', 'سمارٹ', 'ٹیکنالوجی', 'ملازمین', 'کار', 'استعمال', 'ساتھ'], ['ٹیم', 'میچ', 'ٹورنامنٹ', 'ہاکی', 'کرکٹ', 'کپتان', 'کھلاڑیوں', 'کپ', 'بابر', 'سیریز'], ['کورونا', 'وائرس', 'ویکسین', 'ہیلتھ', 'گھنٹوں', 'کیسز', 'ہزار', 'مریض', 'سنٹر', 'ٹیسٹ']]

In [ ]:
# compute Coherence Score CV and NPMI

cm = CoherenceModel(topics=topics_bert, texts=texts, dictionary=id2word, coherence='c_npmi')
coherence = round(cm.get_coherence(),2)
print('\nCoherence Score: ', coherence)

Coherence Score:  0.02

**Diversity Score**

In [ ]:
import itertools
from rbo import rbo
import numpy as np

class InvertedRBO:
    def __init__(self):
        pass

    def irbo(self, topics, topk=10, weight=0.9):
        """
        Calculate inverted Rank Biased Overlap (RBO) as a measure of topic diversity from a list of lists of words.

        :param topics: A list of lists of words representing different topics.
        :param topk: The number of top words on which RBO will be computed.
        :param weight: Weight of each agreement at depth d: p**(d-1). When set to 1.0, there is no weight,
                       and the RBO returns to average overlap.
        :return: The inverted RBO topic diversity score.
        """
        if topk <= 0:
            raise ValueError("topk must be a positive integer.")

        num_topics = len(topics)
        if num_topics == 0:
            raise ValueError("topics list cannot be empty.")

        if topk > len(topics[0]):
            raise Exception('Words in topics are less than topk')

        collect = []
        for list1, list2 in itertools.combinations(topics, 2):
            rbo_val = rbo(list1[:topk], list2[:topk], p=weight)[2]
            collect.append(rbo_val)

        Irbo_score = 1 - np.mean(collect)
        return Irbo_score

In [ ]:
inverted_rbo_calculator = InvertedRBO()
IRBO= round(inverted_rbo_calculator.irbo(topics_bert, topk=10, weight=0.9),2)
print("Inverted RBO Score:", IRBO)

Inverted RBO Score: 1.0

# Visualize Topics

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_barchart(n_words=10,width=220, height=270, title="Topic Word Scores (UNTM)")

# Model serialization

In [ ]:
# Save model
topic_model.save("my_model")

2024-02-04 06:12:01,263 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [ ]:
loaded_topic_model = topic_model.load("my_model")
loaded_topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,78,0_فلم_اداکارہ_اداکار_ویڈیو,"[فلم, اداکارہ, اداکار, ویڈیو, میڈیا, بھارتی, ش...",[ ہدایت کار کامران شاہد کی نئی پاکستانی فلم ہو...
1,1,63,1_عمران_خان_حکومت_الیکشن,"[عمران, خان, حکومت, الیکشن, وزیراعظم, شریف, لی...",[کیا سابق چیف جسٹس گلگت بلتستان نے لندن میں بی...
2,2,62,2_پی_ٹی_سی_پاکستان,"[پی, ٹی, سی, پاکستان, ڈاکٹر, صحت, چیمبر, پنجاب...",[کراچی گوگل کے نیکسٹ بلین یوزرز اقدام کے تحت ...
3,3,57,3_روپے_بک_کمی_مالی,"[روپے, بک, کمی, مالی, فیس, ڈالر, فروخت, فروری,...",[اسلام آباد ریاستہائے متحدہ امریکہ کوویکس کے ...
4,4,54,4_فون_ویوو_اسمارٹ_صارفین,"[فون, ویوو, اسمارٹ, صارفین, سمارٹ, ٹیکنالوجی, ...",[لاہور نے اپنے پہلے اسمارٹ فون کی رونمائی کر د...
5,5,45,5_ٹیم_میچ_ٹورنامنٹ_ہاکی,"[ٹیم, میچ, ٹورنامنٹ, ہاکی, کرکٹ, کپتان, کھلاڑی...",[ نگران وزیراعلی پنجاب سید محسن نقوی کی ہدایت ...
6,6,40,6_کورونا_وائرس_ویکسین_ہیلتھ,"[کورونا, وائرس, ویکسین, ہیلتھ, گھنٹوں, کیسز, ہ...",[ ضلع فیصل آبادکے کوروناویکسی نیشن سنٹرز پراب ...